### ISSUE TITLE
Enquiry about the rotation of anchor box

### ISSUE THREAD

**Issue by GivralNguyen** [duanzhiihao/RAPiD#17]
According to your source code, the anchor box is only vertical . Is this true, or am i missing something? How can the model learn the width, height and angle properly for rotating bounding box when there are no rotated anchors? How does anchors work in your project?  Thanks in advance since i am not sure about this problem .

**Comment by duanzhiihao** [comment]
> According to your source code, the anchor box is only vertical.

Yes, that's true.

> How can the model learn the width, height and angle properly for rotating bounding box when there are no rotated anchors?

We didn't try rotated anchors. The model just miraculously learns how to predict the rotation from vertical anchors. Based on our experiments, the most critical thing is the massive training data from COCO + rotation augmentation. I guess the model somehow learns the pattern of different orientations given enough examples. It also learns the width/height invariant to the orientation. If you want to ask how that works in the internal CNN, that is beyond my knowledge.
Rotated anchors might help, but it will also increase training and testing time complexity.

> How do anchors work in your project?

They are the same as in standard object detection CNNs. We are predicting offsets from the anchors.

**Comment by GivralNguyen** [comment]
After going through some digging and testing with training with COCO, yes the model somehow predicted rotation with vertical anchors . And the way you use anchor box is similar to yolo as well. I have no further questions regarding this issue . Also, can you provide me the link to HABBOF's dataset json? I could not find it anywhere . Much appreciation  to your work.

**Comment by duanzhiihao** [comment]
Sure. The JSON file is along with the image files at http://vip.bu.edu/projects/vsns/cossy/datasets/habbof/.

**Comment by GivralNguyen** [comment]
I tried the provided download link but the there is no json annotation file though. The annotation files are provided in txt form.

**Comment by duanzhiihao** [comment]
Sorry that was my mistake. Could you try to use this script to convert the txt files to JSON file?
https://github.com/duanzhiihao/CEPDOF_tools/blob/master/HABBOF_GtToJSON.py

**Comment by GivralNguyen** [comment]
Converted to json thanks to your code. I will be closing this issue.
