### ISSUE TITLE
Non-person objects in COCO pretraining

### ISSUE THREAD

**Issue by nemtiax** [duanzhiihao/RAPiD#18]
When doing COCO pretraining, do you train on only person objects (only_person=True) or on all objects (only_person=False).  It looks like the code as it stands does the latter, but I'm not sure if this is an indication of the intended algorithm, or if it's a relic of an ablation experiment.    I had originally interpreted Table 4 from the paper as saying that only the person objects are used, but the code (https://github.com/duanzhiihao/RAPiD/blob/12c96998a176bb9d947d61af9a5debb9a0d72127/train.py#L45) has made me second-guess this.

**Comment by duanzhiihao** [comment]
> or if it's a relic of an ablation experiment.

You have a good point, this line is indeed a relic of our ablation experiments.

However, we do train on only person objects, since `args.model='rapid_pL1'` by defualt, which makes `only_person=True`.

I had remove that line to clear up confusion.

**Comment by nemtiax** [comment]
Makes sense, thanks for the clarification!
