### ISSUE TITLE
anchor_size in class RApid :

### ISSUE THREAD

**Issue by lunasdejavu** [duanzhiihao/RAPiD#2]
I found `anchor_size` is not used in `api.py `
```
class Detector():
    '''
    Wrapper of image object detectors.

    Args:
        model_name: str, currently only support 'rapid'
        weights_path: str, path to the pre-trained network weights
        model: torch.nn.Module, used only during training
        conf_thres: float, confidence threshold
        input_size: int, input resolution
    '''
    def __init__(self, model_name='', weights_path=None, model=None, **kwargs):
        assert torch.cuda.is_available()
        if model:
            self.model = model
            return
        if model_name == 'rapid':
            from models.rapid import RAPiD
            model = RAPiD(backbone='dark53', img_norm=False, anchor_size=1024)
```
but it doesn't be used in ` rapid.py`
```
 class RAPiD(nn.Module):
    def __init__(self, backbone='dark53', **kwargs):
        super().__init__()
        anchors = [
            [18.7807, 33.4659], [28.8912, 61.7536], [48.6849, 68.3897],
            [45.0668, 101.4673], [63.0952, 113.5382], [81.3909, 134.4554],
            [91.7364, 144.9949], [137.5189, 178.4791], [194.4429, 250.7985]
        ]
```
so if we didn't use  --high_resolution  with other inputsize so do I have to  change the anchors in `rapid.py`? 
for example 
`anchors = anchors/ 1024 *self.anchor_size`

**Comment by duanzhiihao** [comment]
You are right, we don't use `anchor_size` in `rapid.py`. Actually we did use it, but we find the anchor box size doesn't matter too much, so we deprecated it later. I fixed it in https://github.com/duanzhiihao/RAPiD/commit/fecd9153aeb287552be96af11b3fc1b3636624f2.

`anchors = anchors/ 1024 *self.anchor_size` is a good way to scale the anchor box sizes. But once you set the anchor box size, you should fix it through the entire training and testing phase.
