### ISSUE TITLE
About validation time

### ISSUE THREAD

**Issue by aia39** [duanzhiihao/RAPiD#3]
How much time does it take to validate on 1000 images? We are having some time complexities. We are not sure if there are any problems as we edited some part of your code.

**Comment by duanzhiihao** [comment]
Typically it costs around several minutes to validate on 1000 images, including prediction and metric calculation. The validation time is related to many factors, e.g., input image resolution and the network's precision.

If the network's precision is very low, i.e., it is not well trained, it will produce many garbage predictions that will significantly increase the metric calculation time. It would be great if you could share more detailed information, e.g., the input image resolution and how you train the network.
