### ISSUE TITLE
Confused about a  code snippet

### ISSUE THREAD

**Issue by yzz-cver** [duanzhiihao/RAPiD#32]
Hello, I don't know how to understand the following code snippet. Can you explain the principle?  This code snippet is in the utils/iou_mask.py from line 135 to line 142.
![选区_001](https://user-images.githubusercontent.com/53545589/147200081-2e91d634-7bba-4166-9c79-26ab625c2762.png)

**Comment by duanzhiihao** [comment]
Hi,
For a bounding box with top-left corner `(tl_x, tl_y)` and top-right corner `(tr_x, tr_y)`:
![image](https://user-images.githubusercontent.com/24869582/147272101-164887c4-dfb0-4abf-a607-33151bb243b4.png)

the red dashed line, which pass through `(tl_x, tl_y)` and `(tr_x, tr_y)`, satisfies:
![image](https://user-images.githubusercontent.com/24869582/147272525-2464437c-6214-4c49-9908-210192a75631.png)
You can check it by plugging these two points into the equation.

Now, the first line `mask = (tr_y-tl_y)*gx + (tl_x-tr_x)*gy + tl_y*tr_x - tr_y*tl_x < 0` computes all the points that is below the red dashed line.
![image](https://user-images.githubusercontent.com/24869582/147272978-c277d029-6645-45b5-9818-cac910214e7d.png)

Doing this for all four edges, we have four binary masks, and by multiplying (i.e. logical AND) them together, we get the mask for the bounding box.

**Comment by yzz-cver** [comment]
Okay, thank you!
