### ISSUE TITLE
多类别

### ISSUE THREAD

**Issue by duanyunjie** [duanzhiihao/RAPiD#40]
你好，首先非常感谢您的代码，我想问下如果我想训练WoodScape数据集，代码应该如何修改呢？损失函数是不是也得修改？我看您用是BCE二分类损失函数，谢谢啦

**Comment by duanzhiihao** [comment]
要改的地方请参考这里 https://github.com/duanzhiihao/RAPiD/issues/23#issuecomment-855953921

要做多分类的话，我更建议从一个多分类detector (e.g., yolov5)开始然后给它加上angle loss。这样应该会更容易一些。

**Comment by duanyunjie** [comment]
您好，首先非常感谢您及时回复，目前我按照#23修改了，但是还是有问题，没能调试通，您看您这边可以帮忙解决下吗？有偿的啦，真的太感谢您啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhihao ***@***.***&gt;; 
发送时间: 2022年6月2日(星期四) 晚上10:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [duanzhiihao/RAPiD] 多类别 (Issue #40)





 
要改的地方请参考这里 #23 (comment)
 
要做多分类的话，我更建议从一个多分类detector (e.g., yolov5)开始然后给它加上angle loss。这样应该会更容易一些。

**Comment by duanzhiihao** [comment]
我也很感谢您的兴趣，但是不好意思，1) 我不能收报酬，2) 我最近在忙别的工作，不能抽出很多时间做这个。如果你在改的过程中遇到具体问题，提在issue里我很乐意帮忙(如果我能快速解决的话)，但是更多的事我就没法做了，希望您理解
