### ISSUE TITLE
Can't download Mirror Worlds dataset from the homepage

### ISSUE THREAD

**Issue by hoangnt2601** [duanzhiihao/RAPiD#7]
I can't download this data. Do you have this data set on the google driver?
Thanks

**Comment by duanzhiihao** [comment]
I'm sorry but I don't think I can distribute the data without the permission of the Mirror Worlds dataset organizer. Could you please contact the organizer, [Nuo Ma](https://filebox.ece.vt.edu/~nuoma/), about the dataset download?
